#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export JAVA_HOME=`/usr/libexec/java_home`
export ANDROID_HOME=/usr/local/opt/android-sdk
fpath=(/usr/local/share/zsh-completions $fpath)
